name: Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  setup_meteor:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: "1.10.1"
      - run: yarn install
      - name: Meteor Deploy
        run: METEOR_SESSION_FILE=${{ secrets.TOKEN }} meteor deploy www.bboytools.com --settings ${{ secrets.SETTINGS }}
